language: node_js
dist: trusty
git:
  depth: 1
cache:
  edge: true
  directories:
    - node_modules
    - "$(npm root -g)"
    - "$(npm config get prefix)/bin"
branches:
  only:
    - master
    - stage
    - test
    - dev
env:
  global:
    - DEEP_NO_INTERACTION=1
    # CODECLIMATE_REPO_TOKEN=[secure]
    - secure: "NNMV6wfdQ5Nut9UK3osmpd9NJOkcw9wksNM6j4dfWgsA0vh9U8FeN16zMC7W96g/ZpEZZAJdtqrNpZEwN5dYAn5j7Ksw7gOQ2AQTjKL6qi+PQekDTjshz7PT/dqmvqxYlBdZMK/ExVdpOcrifEfYC67TOfDJ4DBQ/qB966erefRBLucqrawiEEIvdKsBraNv4cPuq/q8BSqKpSajn+I02V90soeKXIFFMHylaHIqPIzNFSJ+ECa36g+Z6UlrrI3R/PN1ApEfmLGDgtsHwjZOZ3PxdhKn0WvIJQh0Sizw3Hq0dBaXV8+2JxlvYmZcr/LJY1wYV6q4JDB14IZr8COL3skHcvKDZMaZmVxVl/zsJEfX+ChNddYwQSZMuhXrR8P/+pw1BY11IMJ5E+Lf1T5+BxmXZqudMoi0PMKpX2m1N7JVajmJ42Lt2WZK/xuN01AP37PYBUh0gw6AmLt/Eg1N1OeNQRJExLAKunkeWYnOqV0R0sngYuqrOr95F0inwds4PjwM0Rp6MfgHfobfmCBX5UQn25p8uGVzCFg9TxdmtnvXw2Vlb3gqlTeuJeieOyYZrQVdwg+W2o1I5RH1wKoh/57/bjQpj0OZX0Aw7e3MRWnsiUh92uvcstQB7kIDdjXdLMNI+S/zb9FEb0IR9WTQtePc57DiMtt6yarYAF1PhPQ="
    # SNYK_API_TOKEN=[secure]
    - secure: "kdArG4ADTmzzpkjJxdZNohJqjnJXbAYF6eN/pj9fh27/P32Vk6tMa3cyMnKitrbhCKD4i2xAw+vlRihRlQkcLVMoNQCMjf9KVFW5EEEw4Uc9WLgWwO0Mp/gnAF8x+o0fim1LTFfJIPpraWb4S1g0nFa2kcEaXNKM25mU/qrXgqaMmRxjwLuXt1/Fs8hfFATZ2QLiaRh3B3SBIGH19uUcpnEXgB92wy0AMYpe/g3Cu8G7L1EnquWyNnEP5pjyrcJWJ4rQmpgkls2W1QsxguckBcy2UuMkweon/SjoQbFqRIaQnLQo1A5Ros6B7JgLogvzqPWpdpliwWVfZaIaIOoBDW4qJTEXmUNpzc4OI6Bj4aPeXU+cZlTUgZxy2PRe4wg/MA5jaYJoVWX4dDlviMXRnO5iiWC6T1TqHdOp/fxkF9PuBvB/x+EpRaKDbP7F0Q/h70Ya7gVmHl2EGplHNBmR7ziYSZC0W6k7exYYscjgexz10BK+i35Hkonbizb2ls5yddClvbho7C2LaRB8ujPsb06q8jtuBYCXFhuHz53D7JIEfx9+0TAImb44zAhkGJzw7M5pufp+RsUs24PgrE+b/b5QvHpLS+taG2I71q0PtZy49wfiMOg+3pedtcci2xq5tfbiNXZ0GNz3FhSlRVRrNJh0AYxYHi0QJWOSx5Gdp2Q="
    # AWS_DEFAULT_REGION=[secure]
    - secure: "YWKjpr054s3GLbC8Zx9FWsgVXZGyp+MZYPCN/Gi2z8l2uubwWeaDeT0qkQxcrlWHN4iXmbGsjEQ0Vx+FbhYUv00Z7Y1H3USZz4YA+jdlrB+kPhIpXUVnJ6t9XA+PJsruF0+/yCRoOpGAx+MWYtMc9aZA75XK6qnkCXErUMyrSKd3wTZMl4e9vcp5knAYxHALEX9lMs2bFnJrI1aWnTkqB4BeVGp2jYhD2BJ+vIwYwT0+VI/3rPphYLvRbex2DpkMPOIXiYeF9+SCp4wYM7DL8BLjKNYl+NwBaWjbMAIpIsEsrPRC9vLVfUqcVogCD2j97QqtyXnvMb/G1K2KBeP2vlud6dUlbTjdv3RBxUoA1uLUsIVuTs3J81xF1baPdD+B1zy6VNY5xdCsS1CHbpTtafTaAq0KdmlsupyBvCKIKQz+KBk9nlGdr9ipL6E1abACj+/4KSn/oPSf3v8E9TXS0XG2FmrPwYOtHVQoDCf6i5yrlQDxlvknJvCrwtCt7j6DhkUKQ8nTyfn7QUf1E8nhg1uogs8BeNI+Loq0J/W4kePZbHicyPS+TAFvm6pzdZVGPhi0IR3YIUjj1+hyd2XadOs5F5kdwl1cJU41zXnC1kFaqHeDWVLl5ekjcfv/gHFU8HVLSNFeaAKUhG4W1CJNM37Qiz2tRo3JbrDW0Cf7S/4="
    # AWS_ACCESS_KEY_ID=[secure]
    - secure: "jFPb6pk4bLRYaGlDFcw+7QZxeFhWyxNLleiL7gX3rCkM4d/dDXQr20w99xfgDLE4+f/Ry6c2tiPXgwAaQpb96XKJcLa2Jnk5++YAV004el0YqUEXn7xKM3AE4cjfPPfKN6kcWJLk1SDT1OH6T875d9yvELlSJS+T0yKlbvRxO+x6xV5EdDNtdUAFn0+Ns8eXFwCtncv1P7CdXLoMeVcE9Uyld3q1E1uRMA9Ec7PPI2lLcJkBFoTK4alyXwaShBEID1EKPzHxtFrhoBXwWqM/r/ZJlkbSHGaVIC77PdKNWbtqQzuBTZuE/HG2nH3sx3r/+KQeGbSW3hmvPtRTBIpMR4bDn8ig46J1k5ugHTAzjqKFGGX8tUaejeb77RQG3i0bqcQgKKqnMSvQ5/dMC/ZHaNHUNtDc/uUeFNBjn/DoaGSBy01wWzpQQ7aMAm4UvCIw1nOUQxmE09rDe5upATc6ls68t6OvwQtDvlyeto455J+kQJvm6BrvwHFK8Lly/qNPqqvAX0d39hux/HnsEFOwMhWEvPzcZdLhefQFsDu6hfdFiGA8xZjq7v9GUw7PGi5UP/TlYx4Cr9cOeNQF/8Ucdh1V1g74fAQ95pUSlVDVST72XrDXZpj1R9kCv8UQr2/T6iEADFjLrHSwhHpJqsQQ5quzBDIGbeY2H1vIHYcBYik="
    # AWS_SECRET_ACCESS_KEY=[secure]
    - secure: "WvYmhf4ZCIqXTaWJ78sFoieuSGUEXhzHh1MpdTjZNiGOsca1PFqKOT0vNNY2litdJg5utlKrw+dJ8lZ2mmehgh9ZnULuLH5FLSeB2Ve0Il1e+aeM/4DGvfziHqRQtRTHdPPMgOL+fC9vKiLMJKOqHE5xFgi8S2kh/1FN/0DPWQEYi7yW22c5sBGpM+ext80xACTpBOn3YYsQqF3mQtPyj84HlXlf4fU2Buj8T57qS18KRdsDMC1AlBanYa6chWIp8pIZexF3i30ylxHp0Dn01gTkTuAK/iemEXIXVPsRhjzBttlJFBOCg8UMvGQCTnkOL4Lr08UeWGT2ghd+bag8fim5x0BWY8hZd6Ub0aYadSH1nHAlR+XPu8/5s9kBQ3MmO5r8rwbvXqay7RmlzQXg7flas6uFtaauuXJfJNe9rS6XdhVdKhbqe4AufyJu6/lpaY54Gn/uUBRE+VXamZ3mQR0PTfyJTEby5Q5N54BTEdvW54aSMHgRDegRrL3RqItNvuAsaM9cydO6gl3TL6tBR048yxEwH/QvEH+w+at5m8b6hBOJOyCHJZZksN/dEe1ukxP/7m3EJFdva+1AcfiOLP0dpQLSnI4PZLnHkGp5DPC9Ve2VrovgCdQuGt75xCUapDfcP6vgAztOHiluH8jCBSJlFOt9J5Ko7uWnVyA3K0E="

stage: "Run Unit Tests :clipboard:"
node_js:
  - 6
  - 8
before_install:
  - bash bin/travis-init.sh
script:
  - recink run unit -c recink-codeclimate -c recink-snyk
