---
engines:
  duplication:
    exclude_paths:
      - "**/tests"
      - "**/lib"
exclude_paths:
  - "**/bin"
  - "**/test"
  - "**/tests"
  - "**/tmp"
  - "**/vendor"
  - "**/lib"
  - "**/.idea"
  - "**.spec.js"
  - "**.min.js"
  - "**.min.css"
  - "**/frontend/_build/"
  - "**/dist"
  - "**/node_modules"
  - "**/packages"
  - "**/font-awesome.css"
  - "**/materialdesignicons.css"
  - "**/DeepFramework.js"
  - "**/deep-framework.js"
